@startuml

title UML-діаграма розгортання ПП

left to right direction

skinparam componentStyle uml1

node "<<Cмартфон>>" as sm {
	node "<<OS Androidx>>" {
		component [.apk]
	}
}

interface TouchScreen

TouchScreen -- sm

@enduml
